/* ============================================================================
 *  IntMap · THE VIETNAM WAR — the curated record
 * ----------------------------------------------------------------------------
 *  The rules every row here obeys — what `control`, `fronts` and `events` are each allowed to claim,
 *  and why a day nobody wrote down gets no line — are stated once, in ./lang.mjs.
 *
 *  ══ THIS WAR IS THE CASE ./lang.mjs WAS WRITTEN FOR ═════════════════════════════════════════
 *  ⚠ FOR MOST OF ITS TWENTY YEARS THERE IS NO QUOTABLE FRONT IN SOUTH VIETNAM, AND THAT IS THE
 *  SUBJECT, NOT A GAP IN THE SOURCES. The two world wars are wars of lines: an army holds a
 *  continuous position, the record states where it ran, and the day it moves someone writes it down.
 *  The war fought in South Vietnam between 1960 and 1972 was not that. Saigon held the cities and the
 *  roads by day; the National Liberation Front held villages inside the same districts, sometimes the
 *  same hamlet after dark. The Americans built an instrument to measure exactly this — the Hamlet
 *  Evaluation System, which scored every hamlet in the country every month — and its own authors,
 *  and the CIA, and the Senate, spent years arguing about what its percentages meant. There is no
 *  line to trace behind those numbers, and there is no honest way to turn a contested percentage
 *  into an area on a map.
 *
 *  So this record does the thing ./lang.mjs says to do where the record has no line: it paints South
 *  Vietnam CONTESTED and says so, in `checks`, on dates inside every one of those spans. That is a
 *  smaller claim than a front, and it is a true one. ⚠ NO AREA IN THIS FILE IS DERIVED FROM HES,
 *  from a pacification score, or from any other percentage.
 *
 *  ══ AND THREE TIMES THERE IS A LINE, SO THREE TIMES THERE IS A FRONT ════════════════════════
 *   1. `dmz` — the Demarcation Line of the 1954 Geneva agreement, on the Bến Hải and the 17th
 *      parallel. It never moves, and it is the ONE line in this war that is written down to the
 *      hamlet. ⚠ IT CUTS NOTHING: it is the border between gw816 and gw817 themselves, so every row
 *      carries `cuts: []` — drawing it is all it has to do, and cutting a country along its own
 *      frontier would be a claim about nothing.
 *   2. `quangtri72` — the Easter Offensive in Quảng Trị, where the PAVN crossed the Demarcation Line
 *      in divisions with armour and the war briefly became a war of lines again: the Cửa Việt river
 *      in April, the Mỹ Chánh in May, the Thạch Hãn from September. ⚠ ONLY QUẢNG TRỊ. The offensive's
 *      other two axes, Kon Tum and An Lộc, were sieges of towns a hundred kilometres inside the
 *      country with no continuous position joining them to anything; they are `events`, not a front.
 *   3. `spring75` — the collapse, which is dated to the day because it was fought and reported as a
 *      conventional campaign. The Highlands went in a week, Huế and Đà Nẵng in five days, and what
 *      the ARVN had left each time was a line across the country that the record names.
 * ==========================================================================*/
import { L } from './lang.mjs';

/* ── the sides ──────────────────────────────────────────────────────────────────────────────────
   The two Vietnamese states and the forces each fought with. ⚠ CONTESTED IS NOT «WE DO NOT KNOW»:
   it is the record's own answer for a country whose control was genuinely divided and whose division
   nobody drew as a boundary. The colours are the ones ./lang.mjs already uses for those two roles. */
const F_VIETNAM = {
  RVN: { col: '#4a7fbd', name: L('Republic of Vietnam and its allies', 'ベトナム共和国（南ベトナム）と同盟国', 'Republik Vietnam und ihre Verbündeten', 'Республика Вьетнам и её союзники', 'República de Vietnam y sus aliados', '越南共和國及其盟國', '越南共和国及其盟国', 'République du Viêt Nam et ses alliés', '베트남 공화국과 동맹국') },
  DRV: { col: '#b4544a', name: L('North Vietnam and the National Liberation Front', 'ベトナム民主共和国（北ベトナム）と南ベトナム解放民族戦線', 'Nordvietnam und die Nationale Befreiungsfront', 'Северный Вьетнам и Национальный фронт освобождения', 'Vietnam del Norte y el Frente Nacional de Liberación', '北越與南越民族解放陣線', '北越与南越民族解放阵线', 'Viêt Nam du Nord et Front national de libération', '북베트남과 남베트남 민족해방전선') },
  CONTESTED: { col: '#c9963c', name: L('Contested — control divided', '争奪中（支配が分かれている）', 'Umkämpft — geteilte Kontrolle', 'Оспаривается — контроль разделён', 'En disputa: control dividido', '交戰中（控制權分裂）', '交战中（控制权分裂）', 'Disputé — contrôle partagé', '교전 중 — 지배 분할') },
  NEUTRAL: { col: '#9aa1a8', name: L('Neutral', '中立', 'Neutral', 'Нейтральные', 'Neutral', '中立', '中立', 'Neutre', '중립') },
};

/* ══════════════════════════════════════════════════════════════════════════════════════════════
 *  THE VIETNAM WAR · 21 July 1954 — 30 April 1975
 *  ⚠ THE WINDOW OPENS ON THE GENEVA AGREEMENT, NOT ON A FIRST SHOT. The war is commonly dated from
 *  1 November 1955, the day the American advisory group in Saigon was stood up; but the thing the
 *  map has to show from its first frame is the line the agreement drew, and that line exists from
 *  21 July 1954. CShapes draws both Vietnams from 1 May 1954 and ends both on 30 April 1975, so the
 *  window this layer can paint and the window the two states existed in are the same window.
 * ════════════════════════════════════════════════════════════════════════════════════════════ */
const VIETNAM = {
  id: 'vietnam',
  name: L('Vietnam War', 'ベトナム戦争', 'Vietnamkrieg', 'Война во Вьетнаме', 'Guerra de Vietnam', '越南戰爭', '越南战争', 'Guerre du Viêt Nam', '베트남 전쟁'),
  from: '1954-07-21', to: '1975-04-30',
  factions: F_VIETNAM,
  /* ⚠ [date, place, the faction that held it]. Half of these rows exist for the reason every war in
     this directory needs them — ⑤ is the only check that can tell a front drawn correctly from one
     drawn back to front — and the other half exist for a reason peculiar to this war: they are the
     record ASSERTING that a span with no line is contested, on a date inside that span. Check ⑪ in
     scripts/build-wars.mjs demands one for every year South Vietnam goes undivided by a front, and
     in this war that is most of the war. Saying «contested» there is the claim; nothing else in the
     file makes it, and without these rows nothing would be looking. */
  checks: [
    /* ── the spans no front crosses, which is where this war mostly lives ─────────────────────── */
    ['1957-07-01', 'Saigon', 'RVN'],          /* before the insurgency: Saigon governs the south */
    ['1966-01-01', 'Saigon', 'CONTESTED'],    /* ⚠ the eleven years the record refuses to draw a line for */
    ['1974-01-01', 'Saigon', 'CONTESTED'],    /* after the Paris ceasefire: «leopard spots», by design */
    ['1965-01-01', 'Hanoi', 'DRV'], ['1975-04-30', 'Hanoi', 'DRV'],
    ['1958-01-01', 'Vientiane', 'NEUTRAL'], ['1969-01-01', 'Vientiane', 'CONTESTED'],
    ['1966-01-01', 'Phnom Penh', 'NEUTRAL'], ['1972-01-01', 'Phnom Penh', 'CONTESTED'],
    ['1960-01-01', 'Udon Thani', 'NEUTRAL'], ['1969-01-01', 'Udon Thani', 'RVN'],
    /* ── Quảng Trị, 1972 — one town from each side of every dated position ───────────────────── */
    /* ⚠ NOT Đông Hà on 10 April, NOT Quảng Trị city on 1 October: both are anchors OF the line that
       decides those days, and a check has to name a place the line does not run through. */
    ['1972-04-10', 'Gio Linh', 'DRV'], ['1972-04-10', 'Hue', 'RVN'],
    ['1972-05-20', 'Quang Tri', 'DRV'], ['1972-05-20', 'Hue', 'RVN'],
    ['1972-10-01', 'Dong Ha', 'DRV'], ['1972-10-01', 'Hue', 'RVN'],
    /* ── the collapse of 1975 ────────────────────────────────────────────────────────────────── */
    ['1975-03-22', 'Pleiku', 'DRV'], ['1975-03-22', 'Kon Tum', 'DRV'], ['1975-03-22', 'Ban Me Thuot', 'DRV'],
    ['1975-03-22', 'Hue', 'RVN'], ['1975-03-22', 'Da Nang', 'RVN'], ['1975-03-22', 'Qui Nhon', 'RVN'],
    ['1975-03-22', 'Nha Trang', 'RVN'],
    ['1975-04-02', 'Da Nang', 'DRV'], ['1975-04-02', 'Da Lat', 'RVN'],
    ['1975-04-12', 'Nha Trang', 'DRV'], ['1975-04-12', 'Cam Ranh', 'DRV'],
    ['1975-04-12', 'Saigon', 'RVN'], ['1975-04-12', 'Ap Bac', 'RVN'],
    ['1975-04-25', 'Phan Thiet', 'DRV'], ['1975-04-25', 'Bien Hoa', 'RVN'], ['1975-04-25', 'Saigon', 'RVN'],
    ['1975-04-30', 'Saigon', 'DRV'],
  ],
  /* gwcode → [[date, faction], …]. A country absent from this table is neutral for the whole war.
     ⚠ CHINA AND THE SOVIET UNION ARE ABSENT ON PURPOSE. Both supplied the DRV on a scale that
     decided the war, and Chinese anti-aircraft and engineer units served inside North Vietnam; but
     neither declared war, neither had a metre of its own territory in the fighting, and painting two
     continents red would be a far larger claim than the one the record supports. The layer's colours
     say who was AT war on their own ground. */
  control: {
    816: [['1954-07-21', 'DRV']],                                       /* North Vietnam, whole and unchanging */
    /* South Vietnam — ⚠ THE WHOLE ARGUMENT OF THIS FILE IS IN THIS ONE ROW. Saigon's writ over the
       countryside broke down after the National Liberation Front was founded on 20 December 1960 and
       was never restored; from that day to the fall of the city the honest colour is «divided», and
       where a line does exist the fronts below cut this country and overrule it. */
    817: [['1954-07-21', 'RVN'], ['1960-12-20', 'CONTESTED'], ['1975-04-30', 'DRV']],
    /* Laos — neutral on paper twice over (1954 and the Geneva declaration of 1962) and a battlefield
       throughout: the Pathet Lao held the north-east, the trail ran down the panhandle, and open
       fighting resumed in July 1959. */
    812: [['1954-07-21', 'NEUTRAL'], ['1959-07-28', 'CONTESTED']],
    /* Cambodia — Sihanouk's neutrality kept the country out of the ground war until the coup of
       18 March 1970; from that day it had a civil war of its own inside this one. */
    811: [['1954-07-21', 'NEUTRAL'], ['1970-03-18', 'CONTESTED']],
    /* the allies, each on the day its first contingent reached South Vietnam — and the United States
       on 1 November 1955, the day the Military Assistance Advisory Group, Vietnam was established,
       which is the American government's own first day of this war */
    2: [['1955-11-01', 'RVN']],
    900: [['1962-08-03', 'RVN']],                                       /* Australia — the AATTV */
    732: [['1964-09-11', 'RVN']],                                       /* South Korea */
    920: [['1965-07-16', 'RVN']],                                       /* New Zealand */
    840: [['1966-09-14', 'RVN']],                                       /* the Philippines — PHILCAG */
    800: [['1967-09-21', 'RVN']],                                       /* Thailand — the Queen's Cobras */
  },
  fronts: [
    {
      /* ⚠ EVERY ROW HERE HAS `cuts: []`. This line is the boundary between gw816 and gw817, so there
         is no country for it to divide — the two Vietnams are already two polygons. What the layer
         does with it is draw it, which is the whole point: the line is on the map from the first
         frame to the last, and the reader can see that the thing everything else in this war was
         about never moved once in twenty-one years. */
      id: 'dmz',
      name: L('The Demarcation Line at the 17th parallel', '17度線（軍事境界線）', 'Die Demarkationslinie am 17. Breitengrad', 'Демаркационная линия по 17-й параллели', 'La línea de demarcación del paralelo 17', '北緯十七度軍事分界線', '北纬十七度军事分界线', 'La ligne de démarcation du 17e parallèle', '17도선 군사분계선'),
      left: 'DRV', right: 'RVN',        /* the line runs east → west, so «left» is the northern side */
      until: '1975-04-30',
      dates: [
        { d: '1954-07-21', cuts: [], note: L('The Geneva agreement fixes a provisional military demarcation line on the Bến Hải river from its mouth at Cửa Tùng to the hamlet of Bồ Hồ Sự, and thence due west to the Laotian frontier — and states that it is not a political or territorial boundary', 'ジュネーヴ協定が暫定軍事境界線を定める——ベン・ハイ川に沿い、河口のクアトゥンからボー・ホー・スー村まで、そこから西へラオス国境まで。協定は「これは政治的・領土的境界ではない」と明記している', 'Das Genfer Abkommen legt eine vorläufige militärische Demarkationslinie fest: am Bến Hải von der Mündung bei Cửa Tùng bis zum Weiler Bồ Hồ Sự und von dort geradewegs westwärts zur laotischen Grenze — und hält fest, dass sie keine politische oder territoriale Grenze ist', 'Женевское соглашение проводит временную военную демаркационную линию по реке Бенхай от устья у Куатунга до селения Бохошы и далее прямо на запад к лаосской границе — и оговаривает, что это не политическая и не территориальная граница', 'El acuerdo de Ginebra fija una línea de demarcación militar provisional sobre el río Bến Hải, desde su desembocadura en Cửa Tùng hasta la aldea de Bồ Hồ Sự, y de allí al oeste hasta la frontera laosiana, y declara que no es una frontera política ni territorial', '日內瓦協定劃定臨時軍事分界線：沿邊海河自河口的Cửa Tùng至Bồ Hồ Sự村，再向西至寮國邊界，並聲明此線並非政治或領土邊界', '日内瓦协定划定临时军事分界线：沿边海河自河口的Cửa Tùng至Bồ Hồ Sự村，再向西至老挝边界，并声明此线并非政治或领土边界', 'L’accord de Genève fixe une ligne de démarcation militaire provisoire sur le Bến Hải, de son embouchure à Cửa Tùng jusqu’au hameau de Bồ Hồ Sự, puis plein ouest vers la frontière laotienne — et précise qu’elle n’est ni une frontière politique ni une frontière territoriale', '제네바 협정이 잠정 군사분계선을 정한다 — 벤하이강을 따라 하구의 끄어뚱에서 보호쓰 마을까지, 거기서 서쪽으로 라오스 국경까지. 협정은 이것이 정치적·영토적 경계가 아니라고 명기한다'),
          pts: ['Cua Tung', 'Huong Lap'] },
        { d: '1956-07-20', cuts: [], note: L('The day the agreement set for nationwide elections passes without them; the provisional line becomes the border of two states', '協定が全国選挙の期日と定めた日が、選挙のないまま過ぎる。暫定線はそのまま二つの国家の国境になる', 'Der im Abkommen für gesamtvietnamesische Wahlen vorgesehene Tag verstreicht ohne Wahlen; die vorläufige Linie wird zur Grenze zweier Staaten', 'Назначенный соглашением день общенациональных выборов проходит без выборов; временная линия становится границей двух государств', 'Pasa sin elecciones el día que el acuerdo fijaba para los comicios en todo el país; la línea provisional se convierte en la frontera de dos Estados', '協定所定的全國選舉之日無選舉而過，臨時分界線就此成為兩個國家的國界', '协定所定的全国选举之日无选举而过，临时分界线就此成为两个国家的国界', 'Le jour prévu par l’accord pour des élections nationales passe sans élections ; la ligne provisoire devient la frontière de deux États', '협정이 전국 선거일로 정한 날이 선거 없이 지나간다. 잠정선은 그대로 두 국가의 국경이 된다'),
          pts: ['Cua Tung', 'Huong Lap'] },
        { d: '1973-01-28', cuts: [], note: L('The Paris ceasefire leaves the line where the Geneva agreement drew it, and leaves everything south of it divided in place', 'パリ和平協定の停戦は、この線をジュネーヴ協定が引いた位置のまま残し、その南のすべてを「その場で分かれたまま」にする', 'Der Waffenstillstand von Paris belässt die Linie dort, wo das Genfer Abkommen sie zog, und lässt alles südlich davon geteilt, wie es steht', 'Парижское перемирие оставляет линию там, где её провело Женевское соглашение, а всё к югу от неё — разделённым на месте', 'El alto el fuego de París deja la línea donde la trazó el acuerdo de Ginebra, y deja todo lo que hay al sur dividido en el sitio', '巴黎停火將此線留在日內瓦協定所劃的位置，並將其以南的一切原地分割', '巴黎停火将此线留在日内瓦协定所划的位置，并将其以南的一切原地分割', 'Le cessez-le-feu de Paris laisse la ligne là où l’accord de Genève l’avait tracée, et laisse tout ce qui est au sud divisé sur place', '파리 휴전은 이 선을 제네바 협정이 그은 자리에 그대로 두고, 그 남쪽의 모든 것을 있는 자리에서 갈라진 채로 남긴다'),
          pts: ['Cua Tung', 'Huong Lap'] },
      ],
    },
    {
      id: 'quangtri72',
      name: L('The Quảng Trị front, 1972', '1972年 クアンチ戦線', 'Die Front in Quảng Trị, 1972', 'Фронт в Куангчи, 1972', 'El frente de Quảng Trị, 1972', '一九七二年廣治戰線', '一九七二年广治战线', 'Le front de Quảng Trị, 1972', '1972년 꽝찌 전선'),
      left: 'DRV', right: 'RVN',        /* the lines run east → west, so «left» is the northern side */
      /* ⚠ IT STOPS AT THE CEASEFIRE. From 28 January 1973 the Paris agreement froze both armies where
         they stood — deliberately, in interlocking pockets nobody drew as a boundary — and a front
         left in place would go on dividing the country into two clean halves it no longer had. */
      until: '1973-01-28',
      dates: [
        { d: '1972-04-02', cuts: [817], note: L('The PAVN crosses the Demarcation Line in three divisions with armour; the northern strongpoints are gone in three days and the ARVN falls back behind the Cửa Việt and Miếu Giang rivers', '北ベトナム軍が3個師団と戦車で軍事境界線を越える。北部の拠点は3日で失われ、南ベトナム軍はクアヴィエト川・ミエウザン川の南岸へ後退する', 'Die PAVN überschreitet die Demarkationslinie mit drei Divisionen und Panzern; die nördlichen Stützpunkte fallen in drei Tagen, die ARVN geht hinter Cửa Việt und Miếu Giang zurück', 'АНВ переходит демаркационную линию тремя дивизиями с танками; северные опорные пункты падают за три дня, и АРВ отходит за реки Куавьет и Мьеужанг', 'El EPV cruza la línea de demarcación con tres divisiones y blindados; los puntos fuertes del norte caen en tres días y el ARVN retrocede tras los ríos Cửa Việt y Miếu Giang', '北越人民軍以三個師與裝甲部隊越過軍事分界線；北部據點三日內盡失，南越軍退守Cửa Việt與Miếu Giang兩河之南', '北越人民军以三个师与装甲部队越过军事分界线；北部据点三日内尽失，南越军退守Cửa Việt与Miếu Giang两河之南', 'L’APVN franchit la ligne de démarcation avec trois divisions et des blindés ; les points d’appui du nord tombent en trois jours et l’ARVN se replie derrière les rivières Cửa Việt et Miếu Giang', '북베트남군이 3개 사단과 기갑으로 군사분계선을 넘는다. 북부 거점들은 사흘 만에 사라지고, 남베트남군은 끄어비엣강과 미에우장강 남안으로 물러난다'),
          pts: ['Cua Viet', 'Dong Ha', 'Cam Lo', 'Lao Bao'] },
        { d: '1972-05-02', cuts: [817], note: L('Quảng Trị city has fallen — the first provincial capital the North takes and holds — and the ARVN stops on the Mỹ Chánh river, the last position in front of Huế', 'クアンチ市が陥落——北ベトナムが奪って保持した最初の省都——南ベトナム軍はフエ手前の最後の陣地、ミーチャン川で踏みとどまる', 'Quảng Trị ist gefallen — die erste Provinzhauptstadt, die der Norden nimmt und hält — und die ARVN kommt am Mỹ Chánh zum Stehen, der letzten Stellung vor Huế', 'Куангчи пал — первая провинциальная столица, взятая Севером и удержанная, — и АРВ останавливается на реке Мичань, последней позиции перед Хюэ', 'Ha caído la ciudad de Quảng Trị —la primera capital provincial que el Norte toma y conserva— y el ARVN se detiene en el río Mỹ Chánh, la última posición ante Huế', '廣治市陷落——北方奪取並守住的第一座省會——南越軍在順化之前的最後陣地美政河停下', '广治市陷落——北方夺取并守住的第一座省会——南越军在顺化之前的最后阵地美政河停下', 'Quảng Trị est tombée — la première capitale provinciale que le Nord prend et conserve — et l’ARVN s’arrête sur la rivière Mỹ Chánh, dernière position devant Huế', '꽝찌 시가 함락된다 — 북측이 빼앗아 지켜낸 첫 성도(省都) — 남베트남군은 후에 앞의 마지막 진지인 미짜인강에서 멈춘다'),
          pts: ['My Chanh', 'Lao Bao'] },
        { d: '1972-09-16', cuts: [817], note: L('After eighty-one days the ARVN retakes the citadel of Quảng Trị; the front settles on the Thạch Hãn and stays there until the ceasefire', '81日をかけて南ベトナム軍がクアンチの城塞を奪回する。戦線はタクハン川で固まり、停戦までそこにとどまる', 'Nach einundachtzig Tagen nimmt die ARVN die Zitadelle von Quảng Trị zurück; die Front setzt sich am Thạch Hãn fest und bleibt dort bis zum Waffenstillstand', 'После восьмидесяти одного дня АРВ отбивает цитадель Куангчи; фронт встаёт на Тхатьхане и стоит там до перемирия', 'Tras ochenta y un días el ARVN recupera la ciudadela de Quảng Trị; el frente se fija en el Thạch Hãn y allí queda hasta el alto el fuego', '歷八十一日，南越軍奪回廣治城堡；戰線固定於石漢河，直至停火', '历八十一日，南越军夺回广治城堡；战线固定于石汉河，直至停火', 'Après quatre-vingt-un jours l’ARVN reprend la citadelle de Quảng Trị ; le front se fixe sur le Thạch Hãn et y reste jusqu’au cessez-le-feu', '81일 만에 남베트남군이 꽝찌 성채를 탈환한다. 전선은 타익한강에 자리잡아 휴전까지 그대로 있는다'),
          pts: ['Cua Viet', 'Quang Tri', 'Lao Bao'] },
      ],
    },
    {
      id: 'spring75',
      name: L('The 1975 Spring Offensive', '1975年 春季攻勢', 'Die Frühjahrsoffensive 1975', 'Весеннее наступление 1975 года', 'La ofensiva de primavera de 1975', '一九七五年春季攻勢', '一九七五年春季攻势', 'L’offensive du printemps 1975', '1975년 춘계 공세'),
      left: 'DRV', right: 'RVN',
      dates: [
        { d: '1975-03-20', cuts: [817], note: L('Ban Mê Thuột fell on 11 March and Saigon ordered the Central Highlands abandoned; the column leaving Pleiku and Kon Tum is destroyed on Route 7B, and Quảng Trị is given up the same week. Two of the country’s four corps areas have gone in ten days', 'バンメトートが3月11日に陥落し、サイゴンは中部高原の放棄を命じた。プレイク・コントゥムから退く車列は国道7B号で壊滅し、同じ週にクアンチも放棄される。10日間で4個軍団管区のうち2つが失われた', 'Ban Mê Thuột fiel am 11. März, und Saigon befahl die Räumung des zentralen Hochlands; die Kolonne aus Pleiku und Kon Tum wird auf der Straße 7B vernichtet, und in derselben Woche wird Quảng Trị aufgegeben. Zwei der vier Korpsbereiche des Landes sind in zehn Tagen verloren', 'Банметхуот пал 11 марта, и Сайгон приказал оставить Центральное плато; колонна, уходящая из Плейку и Контума, гибнет на дороге 7B, и на той же неделе оставлен Куангчи. Две из четырёх корпусных зон страны исчезли за десять дней', 'Ban Mê Thuột cayó el 11 de marzo y Saigón ordenó abandonar las Tierras Altas Centrales; la columna que sale de Pleiku y Kon Tum es destruida en la ruta 7B, y esa misma semana se cede Quảng Trị. Dos de las cuatro zonas de cuerpo del país han desaparecido en diez días', '邦美蜀於三月十一日陷落，西貢下令放棄中部高原；自波來古與昆嵩撤出的車隊在7B號公路上被殲滅，同週廣治亦被放棄。十日之內，全國四個軍區去其二', '邦美蜀于三月十一日陷落，西贡下令放弃中部高原；自波来古与昆嵩撤出的车队在7B号公路上被歼灭，同周广治亦被放弃。十日之内，全国四个军区去其二', 'Ban Mê Thuột est tombée le 11 mars et Saigon a ordonné l’abandon des Hauts Plateaux ; la colonne partie de Pleiku et Kon Tum est détruite sur la route 7B, et Quảng Trị est cédée la même semaine. Deux des quatre zones de corps d’armée du pays ont disparu en dix jours', '반메투옷이 3월 11일에 함락되고 사이공은 중부 고원 포기를 명령했다. 쁠래이꾸와 꼰뚬에서 빠져나온 행렬은 7B번 도로에서 궤멸하고, 같은 주에 꽝찌도 포기된다. 열흘 만에 네 개 군단 관구 중 둘이 사라졌다'),
          pts: ['My Chanh', 'A Luoi', 'Kham Duc', 'An Khe', 'Khanh Duong', 'Loc Ninh'] },
        { d: '1975-03-31', cuts: [817], note: L('Huế was abandoned on 25 March and Đà Nẵng, with a million people inside it, fell on the 29th; the ARVN’s remaining front on the coast is at Quy Nhơn', 'フエは3月25日に放棄され、100万人を抱えたダナンは29日に陥落した。沿岸で南ベトナム軍に残された前線はクイニョンにある', 'Huế wurde am 25. März geräumt, und Đà Nẵng mit einer Million Menschen darin fiel am 29.; die verbliebene Front der ARVN an der Küste liegt bei Quy Nhơn', 'Хюэ оставлен 25 марта, а Дананг с миллионом человек внутри пал 29-го; оставшийся фронт АРВ на побережье — у Куинёна', 'Huế fue abandonada el 25 de marzo y Đà Nẵng, con un millón de personas dentro, cayó el 29; el frente que le queda al ARVN en la costa está en Quy Nhơn', '順化於三月二十五日棄守，容納百萬人的峴港於二十九日陷落；南越軍在沿海僅存的戰線在歸仁', '顺化于三月二十五日弃守，容纳百万人的岘港于二十九日陷落；南越军在沿海仅存的战线在归仁', 'Huế a été abandonnée le 25 mars et Đà Nẵng, avec un million de personnes à l’intérieur, est tombée le 29 ; le front qui reste à l’ARVN sur la côte est à Quy Nhơn', '후에는 3월 25일에 포기되고, 백만 명을 품은 다낭은 29일에 함락되었다. 해안에 남은 남베트남군의 전선은 꾸이년에 있다'),
          pts: ['Qui Nhon', 'Khanh Duong', 'Loc Ninh'] },
        { d: '1975-04-09', cuts: [817], note: L('Nha Trang, Cam Ranh and Đà Lạt are gone and Saigon tries to hold a last line from Phan Rang through Xuân Lộc to Tây Ninh; the battle for Xuân Lộc opens today', 'ニャチャン・カムラン・ダラットが失われ、サイゴンはファンラン——スアンロク——タイニンの最後の線を守ろうとする。スアンロクの戦いは本日始まる', 'Nha Trang, Cam Ranh und Đà Lạt sind verloren, und Saigon versucht eine letzte Linie von Phan Rang über Xuân Lộc nach Tây Ninh zu halten; die Schlacht um Xuân Lộc beginnt heute', 'Нячанг, Камрань и Далат потеряны, и Сайгон пытается удержать последнюю линию от Фанранга через Суанлок к Тэйниню; сегодня начинается бой за Суанлок', 'Nha Trang, Cam Ranh y Đà Lạt se han perdido y Saigón intenta sostener una última línea de Phan Rang a Tây Ninh pasando por Xuân Lộc; hoy empieza la batalla de Xuân Lộc', '芽莊、金蘭與大叻已失，西貢試圖守住由潘朗經春祿至西寧的最後一線；春祿之戰於今日展開', '芽庄、金兰与大叻已失，西贡试图守住由潘朗经春禄至西宁的最后一线；春禄之战于今日展开', 'Nha Trang, Cam Ranh et Đà Lạt sont perdues et Saigon tente de tenir une dernière ligne de Phan Rang à Tây Ninh par Xuân Lộc ; la bataille de Xuân Lộc s’ouvre aujourd’hui', '냐짱·깜라인·달랏이 사라지고, 사이공은 판랑에서 쑤언록을 거쳐 떠이닌으로 이어지는 마지막 선을 지키려 한다. 쑤언록 전투가 오늘 시작된다'),
          pts: ['Phan Rang', 'Xuan Loc', 'Tay Ninh'] },
        { d: '1975-04-22', cuts: [817], note: L('Phan Rang fell on 16 April, Phan Thiết on the 19th and Xuân Lộc yesterday; what is left of the front stands forty kilometres from Saigon', 'ファンランは4月16日、ファンティエットは19日、スアンロクは昨日陥落した。残された戦線はサイゴンから40キロの位置にある', 'Phan Rang fiel am 16. April, Phan Thiết am 19. und Xuân Lộc gestern; was von der Front übrig ist, steht vierzig Kilometer vor Saigon', 'Фанранг пал 16 апреля, Фантхьет — 19-го, Суанлок — вчера; то, что осталось от фронта, стоит в сорока километрах от Сайгона', 'Phan Rang cayó el 16 de abril, Phan Thiết el 19 y Xuân Lộc ayer; lo que queda del frente está a cuarenta kilómetros de Saigón', '潘朗於四月十六日、潘切於十九日、春祿於昨日陷落；殘存的戰線距西貢四十公里', '潘朗于四月十六日、潘切于十九日、春禄于昨日陷落；残存的战线距西贡四十公里', 'Phan Rang est tombée le 16 avril, Phan Thiết le 19 et Xuân Lộc hier ; ce qui reste du front se tient à quarante kilomètres de Saigon', '판랑은 4월 16일, 판티엣은 19일, 쑤언록은 어제 함락되었다. 남은 전선은 사이공에서 40킬로미터 앞에 서 있다'),
          pts: ['La Gi', 'Xuan Loc', 'Tay Ninh'] },
        /* ⚠ AN EMPTY LINE, WHICH IS HOW THIS FILE SAYS «THERE IS NOTHING LEFT TO DIVIDE». Saigon
           surrendered at 11:30, the Republic of Vietnam ceased to exist, and CShapes ends gw817 on
           this very day. `control` takes the country back and paints it whole. */
        { d: '1975-04-30', cuts: [], pts: [], note: L('Saigon surrenders at 11:30; the Republic of Vietnam ceases to exist and there is no longer a line inside it', '11時30分、サイゴン降伏。ベトナム共和国は消滅し、その内側にはもう線が無い', 'Saigon kapituliert um 11:30 Uhr; die Republik Vietnam hört auf zu bestehen, und es gibt keine Linie mehr in ihr', 'В 11:30 Сайгон капитулирует; Республика Вьетнам прекращает существование, и линии внутри неё больше нет', 'Saigón se rinde a las 11:30; la República de Vietnam deja de existir y ya no hay línea alguna en su interior', '十一時三十分西貢投降；越南共和國不復存在，其內再無戰線', '十一时三十分西贡投降；越南共和国不复存在，其内再无战线', 'Saigon capitule à 11 h 30 ; la République du Viêt Nam cesse d’exister et il n’y a plus de ligne à l’intérieur', '11시 30분 사이공이 항복한다. 베트남 공화국은 소멸하고, 그 안에는 더 이상 선이 없다') },
      ],
    },
  ],
  events: [
    { d: '1954-04-26', d2: '1954-07-21', at: 'Geneva', wiki: 'Geneva_Conference_(1954)', kind: 'conference', name: L('Geneva Conference — Indochina is partitioned at the 17th parallel', 'ジュネーヴ会議——インドシナは17度線で分割される', 'Genfer Konferenz — Indochina wird am 17. Breitengrad geteilt', 'Женевская конференция — Индокитай разделён по 17-й параллели', 'Conferencia de Ginebra: Indochina queda dividida en el paralelo 17', '日內瓦會議——印度支那以北緯十七度分割', '日内瓦会议——印度支那以北纬十七度分割', 'Conférence de Genève — l’Indochine est partagée au 17e parallèle', '제네바 회담 — 인도차이나가 17도선에서 분할되다') },
    { d: '1955-10-26', at: 'Saigon', wiki: '1955_State_of_Vietnam_referendum', kind: 'political', name: L('The Republic of Vietnam is proclaimed in Saigon after a rigged referendum deposes Bảo Đại', '不正な国民投票でバオダイが退けられ、サイゴンでベトナム共和国が宣言される', 'Nach einem manipulierten Referendum, das Bảo Đại absetzt, wird in Saigon die Republik Vietnam ausgerufen', 'После сфальсифицированного референдума, низложившего Бао Дая, в Сайгоне провозглашена Республика Вьетнам', 'Tras un referéndum amañado que depone a Bảo Đại, se proclama en Saigón la República de Vietnam', '一場舞弊公投廢黜保大後，越南共和國在西貢宣告成立', '一场舞弊公投废黜保大后，越南共和国在西贡宣告成立', 'Après un référendum truqué qui dépose Bảo Đại, la République du Viêt Nam est proclamée à Saigon', '부정 국민투표로 바오다이가 폐위된 뒤, 사이공에서 베트남 공화국이 선포되다') },
    { d: '1960-12-20', at: 'Tay Ninh', wiki: 'Viet_Cong', kind: 'uprising', name: L('The National Liberation Front is founded in Tây Ninh province', 'タイニン省で南ベトナム解放民族戦線が結成される', 'In der Provinz Tây Ninh wird die Nationale Befreiungsfront gegründet', 'В провинции Тэйнинь основан Национальный фронт освобождения', 'Se funda el Frente Nacional de Liberación en la provincia de Tây Ninh', '南越民族解放陣線於西寧省成立', '南越民族解放阵线于西宁省成立', 'Le Front national de libération est fondé dans la province de Tây Ninh', '떠이닌성에서 남베트남 민족해방전선이 결성되다') },
    { d: '1963-01-02', at: 'Ap Bac', wiki: 'Battle_of_Ap_Bac', kind: 'battle', name: L('Battle of Ấp Bắc — a Viet Cong battalion stands and beats a force five times its size', 'アプバクの戦い——解放戦線の1個大隊が踏みとどまり、5倍の兵力を撃退する', 'Schlacht von Ấp Bắc — ein Vietcong-Bataillon stellt sich und schlägt eine fünffach überlegene Streitmacht', 'Бой при Апбак — батальон Вьетконга принимает бой и разбивает впятеро превосходящие силы', 'Batalla de Ấp Bắc: un batallón del Vietcong planta cara y derrota a una fuerza cinco veces mayor', '北村之戰——越共一個營堅守並擊敗五倍於己的兵力', '北村之战——越共一个营坚守并击败五倍于己的兵力', 'Bataille d’Ấp Bắc — un bataillon vietcong tient et bat une force cinq fois supérieure', '업박 전투 — 베트콩 1개 대대가 버티며 다섯 배의 병력을 물리치다') },
    { d: '1963-06-11', at: 'Saigon', wiki: 'Thích_Quảng_Đức', kind: 'uprising', name: L('Thích Quảng Đức burns himself at a Saigon crossroads, and the Buddhist crisis becomes visible to the world', 'ティック・クアン・ドックがサイゴンの交差点で焼身する。仏教徒危機が世界の目に触れる', 'Thích Quảng Đức verbrennt sich an einer Kreuzung in Saigon, und die Buddhistenkrise wird der Welt sichtbar', 'Тхить Куанг Дык совершает самосожжение на перекрёстке в Сайгоне, и буддийский кризис становится виден всему миру', 'Thích Quảng Đức se inmola en un cruce de Saigón y la crisis budista se hace visible ante el mundo', '釋廣德在西貢街口自焚，佛教危機為世人所見', '释广德在西贡街口自焚，佛教危机为世人所见', 'Thích Quảng Đức s’immole à un carrefour de Saigon, et la crise bouddhiste devient visible au monde entier', '틱꽝득이 사이공의 교차로에서 소신공양하고, 불교도 위기가 세계에 드러나다') },
    { d: '1963-11-01', d2: '1963-11-02', at: 'Saigon', wiki: '1963_South_Vietnamese_coup', kind: 'political', name: L('The generals’ coup: Ngô Đình Diệm is overthrown and killed', '軍部クーデター——ゴ・ディン・ジエムが打倒され、殺害される', 'Der Putsch der Generäle: Ngô Đình Diệm wird gestürzt und getötet', 'Переворот генералов: Нго Динь Зьем свергнут и убит', 'El golpe de los generales: Ngô Đình Diệm es derrocado y asesinado', '將領政變——吳廷琰被推翻並遭殺害', '将领政变——吴廷琰被推翻并遭杀害', 'Le coup d’État des généraux : Ngô Đình Diệm est renversé et tué', '장군들의 쿠데타 — 응오딘지엠이 축출되고 살해되다') },
    { d: '1964-08-02', d2: '1964-08-04', at: 'Gulf of Tonkin', wiki: 'Gulf_of_Tonkin_incident', kind: 'naval', name: L('Gulf of Tonkin incident — one engagement on 2 August, and a second on the 4th that did not happen', 'トンキン湾事件——8月2日の交戦と、8月4日の「起きなかった」交戦', 'Tonkin-Zwischenfall — ein Gefecht am 2. August und ein zweites am 4., das es nicht gab', 'Тонкинский инцидент — бой 2 августа и второй, 4-го, которого не было', 'Incidente del golfo de Tonkín: un combate el 2 de agosto y un segundo, el día 4, que nunca ocurrió', '北部灣事件——八月二日的交戰，與八月四日那場並未發生的交戰', '北部湾事件——八月二日的交战，与八月四日那场并未发生的交战', 'Incident du golfe du Tonkin — un engagement le 2 août, et un second le 4 qui n’a pas eu lieu', '통킹만 사건 — 8월 2일의 교전과, 일어나지 않은 8월 4일의 교전') },
    { d: '1964-08-07', at: 'Washington', wiki: 'Gulf_of_Tonkin_Resolution', kind: 'political', name: L('The Gulf of Tonkin Resolution gives the President war powers without a declaration of war', 'トンキン湾決議——宣戦布告なしに大統領へ戦争権限が与えられる', 'Die Tonkin-Resolution gibt dem Präsidenten Kriegsvollmachten ohne Kriegserklärung', 'Тонкинская резолюция даёт президенту военные полномочия без объявления войны', 'La Resolución del golfo de Tonkín otorga al presidente poderes de guerra sin declaración de guerra', '北部灣決議案在未宣戰的情況下賦予總統戰爭權力', '北部湾决议案在未宣战的情况下赋予总统战争权力', 'La résolution du golfe du Tonkin donne au président les pouvoirs de guerre sans déclaration de guerre', '통킹만 결의 — 선전포고 없이 대통령에게 전쟁 권한을 부여하다') },
    { d: '1965-02-07', at: 'Pleiku', wiki: 'Operation_Flaming_Dart', kind: 'air', name: L('Camp Holloway at Pleiku is attacked, and the reprisal strikes of Flaming Dart begin the air war against the North', 'プレイクのキャンプ・ハロウェイが襲撃され、報復のフレイミング・ダート作戦が北爆の始まりとなる', 'Camp Holloway bei Pleiku wird angegriffen, und die Vergeltungsschläge der Operation Flaming Dart eröffnen den Luftkrieg gegen den Norden', 'Нападение на лагерь Холлоуэй под Плейку; ответные удары операции «Флеминг Дарт» открывают воздушную войну против Севера', 'Atacan Camp Holloway, en Pleiku, y las represalias de Flaming Dart inician la guerra aérea contra el Norte', '波來古的霍洛威營遭襲，報復性的「火焰標槍」行動揭開對北方的空戰', '波来古的霍洛威营遭袭，报复性的“火焰标枪”行动揭开对北方的空战', 'Le camp Holloway, à Pleiku, est attaqué, et les représailles de Flaming Dart ouvrent la guerre aérienne contre le Nord', '쁠래이꾸의 할러웨이 기지가 습격당하고, 보복 작전 플레이밍 다트가 북폭의 시작이 되다') },
    { d: '1965-03-02', d2: '1968-11-02', at: 'Vinh', wiki: 'Operation_Rolling_Thunder', kind: 'air', name: L('Operation Rolling Thunder — three and a half years of graduated bombing of North Vietnam', 'ローリング・サンダー作戦——3年半にわたる北ベトナムへの段階的爆撃', 'Operation Rolling Thunder — dreieinhalb Jahre abgestufter Bombardierung Nordvietnams', 'Операция «Раскаты грома» — три с половиной года эскалационных бомбардировок Северного Вьетнама', 'Operación Rolling Thunder: tres años y medio de bombardeo gradual de Vietnam del Norte', '「滾雷」行動——對北越為期三年半的逐步升級轟炸', '“滚雷”行动——对北越为期三年半的逐步升级轰炸', 'Opération Rolling Thunder — trois ans et demi de bombardement gradué du Viêt Nam du Nord', '롤링 선더 작전 — 3년 반에 걸친 북베트남 단계적 폭격') },
    { d: '1965-03-08', at: 'Da Nang', wiki: 'Da_Nang_Air_Base', kind: 'landing', name: L('Two Marine battalions land at Đà Nẵng — the first American ground combat troops in Vietnam', '海兵隊の2個大隊がダナンに上陸——ベトナムに入った最初のアメリカ地上戦闘部隊', 'Zwei Marineinfanterie-Bataillone landen bei Đà Nẵng — die ersten amerikanischen Bodenkampftruppen in Vietnam', 'Два батальона морской пехоты высаживаются в Дананге — первые американские наземные боевые части во Вьетнаме', 'Dos batallones de marines desembarcan en Đà Nẵng: las primeras tropas de combate terrestres estadounidenses en Vietnam', '兩個陸戰隊營於峴港登陸——美軍進入越南的第一批地面作戰部隊', '两个陆战队营于岘港登陆——美军进入越南的第一批地面作战部队', 'Deux bataillons de Marines débarquent à Đà Nẵng — les premières troupes de combat terrestres américaines au Viêt Nam', '해병 2개 대대가 다낭에 상륙하다 — 베트남에 투입된 최초의 미 지상 전투부대') },
    { d: '1965-04-03', d2: '1968-11-11', at: 'Tchepone', wiki: 'Operation_Steel_Tiger', kind: 'air', name: L('Operation Steel Tiger — the air campaign against the Hồ Chí Minh trail in the Laotian panhandle', 'スチール・タイガー作戦——ラオス南部を走るホーチミン・ルートへの航空作戦', 'Operation Steel Tiger — der Luftkrieg gegen den Ho-Chi-Minh-Pfad im laotischen Panhandle', 'Операция «Стальной тигр» — воздушная кампания против тропы Хо Ши Мина в лаосском «панхандле»', 'Operación Steel Tiger: la campaña aérea contra la ruta Hồ Chí Minh en el corredor laosiano', '「鋼虎」行動——針對寮國南部走廊胡志明小道的空中作戰', '“钢虎”行动——针对老挝南部走廊胡志明小道的空中作战', 'Opération Steel Tiger — la campagne aérienne contre la piste Hô Chi Minh dans le couloir laotien', '스틸 타이거 작전 — 라오스 남부 회랑의 호찌민 루트를 겨냥한 항공 작전') },
    { d: '1965-08-18', d2: '1965-08-24', at: 'Chu Lai', wiki: 'Operation_Starlite', kind: 'battle', name: L('Operation Starlite — the first major American ground battle of the war, south of Chu Lai', 'スターライト作戦——チューライ南方で行われた、アメリカ軍最初の大規模地上戦', 'Operation Starlite — die erste größere amerikanische Bodenschlacht des Krieges, südlich von Chu Lai', 'Операция «Старлайт» — первое крупное наземное сражение американцев в этой войне, южнее Чулай', 'Operación Starlite: la primera gran batalla terrestre estadounidense de la guerra, al sur de Chu Lai', '「星光」行動——美軍在本戰爭中的首場大規模地面戰，於朱萊以南', '“星光”行动——美军在本战争中的首场大规模地面战，于朱莱以南', 'Opération Starlite — la première grande bataille terrestre américaine de la guerre, au sud de Chu Lai', '스타라이트 작전 — 쭈라이 남쪽에서 벌어진 미군 최초의 대규모 지상전') },
    { d: '1965-11-14', d2: '1965-11-18', at: 'Ia Drang', wiki: 'Battle_of_Ia_Drang', kind: 'battle', name: L('Battle of the Ia Drang — the first meeting of the US Army and the PAVN in strength', 'イア・ドラン渓谷の戦い——アメリカ陸軍と北ベトナム軍が本格的に衝突した最初の戦い', 'Schlacht im Ia-Drang-Tal — das erste Aufeinandertreffen von US-Heer und PAVN in großer Stärke', 'Битва в долине Йа-Дранг — первое крупное столкновение армии США и АНВ', 'Batalla del valle de Ia Drang: el primer encuentro en fuerza entre el Ejército de EE. UU. y el EPV', '德浪河谷之戰——美國陸軍與北越人民軍首次大規模交鋒', '德浪河谷之战——美国陆军与北越人民军首次大规模交锋', 'Bataille de la Ia Drang — la première rencontre en force entre l’armée américaine et l’APVN', '이아드랑 전투 — 미 육군과 북베트남군의 첫 본격적 격돌') },
    { d: '1966-08-18', at: 'Long Tan', wiki: 'Battle_of_Long_Tan', kind: 'battle', name: L('Battle of Long Tân — one Australian company holds off a regiment in a rubber plantation', 'ロンタンの戦い——ゴム農園で、オーストラリア軍の1個中隊が1個連隊を食い止める', 'Schlacht von Long Tân — eine australische Kompanie hält in einer Kautschukplantage ein Regiment auf', 'Бой при Лонгтане — одна австралийская рота сдерживает полк на каучуковой плантации', 'Batalla de Long Tân: una compañía australiana contiene a un regimiento en una plantación de caucho', '隆潭之戰——一個澳軍連在橡膠園中擋住一個團', '隆潭之战——一个澳军连在橡胶园中挡住一个团', 'Bataille de Long Tân — une compagnie australienne contient un régiment dans une plantation d’hévéas', '롱딴 전투 — 고무 농장에서 호주군 1개 중대가 1개 연대를 막아내다') },
    { d: '1967-01-08', d2: '1967-01-26', at: 'Ben Cat', wiki: 'Operation_Cedar_Falls', kind: 'battle', name: L('Operation Cedar Falls — the Iron Triangle is cleared and Bến Súc is emptied and razed', 'シーダー・フォールズ作戦——「鉄の三角地帯」が掃討され、ベンスックは住民を移されて焼き払われる', 'Operation Cedar Falls — das Eiserne Dreieck wird geräumt, Bến Súc entvölkert und dem Erdboden gleichgemacht', 'Операция «Сидар-Фолс» — «Железный треугольник» зачищен, Бенсук выселен и снесён', 'Operación Cedar Falls: se despeja el Triángulo de Hierro y Bến Súc es vaciada y arrasada', '「杉瀑」行動——鐵三角遭清剿，Bến Súc村被遷空並夷平', '“杉瀑”行动——铁三角遭清剿，Bến Súc村被迁空并夷平', 'Opération Cedar Falls — le Triangle de fer est nettoyé et Bến Súc vidée puis rasée', '시더 폴스 작전 — 철의 삼각지대가 소탕되고, 벤쑥 마을은 주민이 옮겨진 뒤 밀려 없어지다') },
    { d: '1967-02-22', d2: '1967-05-14', at: 'Tay Ninh', wiki: 'Operation_Junction_City', kind: 'battle', name: L('Operation Junction City — the largest American operation of the war, and the war’s only US combat parachute drop', 'ジャンクション・シティ作戦——アメリカ軍として最大の作戦であり、この戦争唯一の米軍戦闘降下', 'Operation Junction City — die größte amerikanische Operation des Krieges und der einzige US-Kampfsprung dieses Krieges', 'Операция «Джанкшен-Сити» — крупнейшая американская операция войны и единственная боевая выброска парашютистов США в ней', 'Operación Junction City: la mayor operación estadounidense de la guerra y su único salto de combate en paracaídas', '「交會城」行動——美軍在本戰爭中規模最大的作戰，也是唯一一次美軍戰鬥傘降', '“交会城”行动——美军在本战争中规模最大的作战，也是唯一一次美军战斗伞降', 'Opération Junction City — la plus grande opération américaine de la guerre et son unique saut de combat en parachute', '정션 시티 작전 — 미군 최대 규모의 작전이자, 이 전쟁 유일의 미군 전투 강하') },
    { d: '1967-11-03', d2: '1967-11-22', at: 'Dak To', wiki: 'Battle_of_Dak_To', kind: 'battle', name: L('Battle of Đắk Tô — three weeks for the hills above the town, and Hill 875', 'ダクトーの戦い——町を見下ろす丘をめぐる3週間、そして875高地', 'Schlacht von Đắk Tô — drei Wochen um die Höhen über dem Ort, und Hügel 875', 'Бой за Дакто — три недели за высоты над городком и за высоту 875', 'Batalla de Đắk Tô: tres semanas por las colinas sobre el pueblo, y la cota 875', '達克托之戰——為城鎮上方諸高地鏖戰三週，以及875高地', '达克托之战——为城镇上方诸高地鏖战三周，以及875高地', 'Bataille de Đắk Tô — trois semaines pour les collines dominant la ville, et la cote 875', '닥또 전투 — 마을을 굽어보는 고지들을 둘러싼 3주, 그리고 875고지') },
    { d: '1968-01-21', d2: '1968-07-09', at: 'Khe Sanh', wiki: 'Battle_of_Khe_Sanh', kind: 'siege', name: L('Siege of Khe Sanh — seventy-seven days of encirclement, and a base abandoned five months later', 'ケサンの包囲——77日間の包囲戦。基地はその5か月後に放棄される', 'Belagerung von Khe Sanh — siebenundsiebzig Tage Einschließung, und fünf Monate später wird die Basis aufgegeben', 'Осада Кхесани — семьдесят семь дней окружения; базу оставят пять месяцев спустя', 'Asedio de Khe Sanh: setenta y siete días de cerco, y una base abandonada cinco meses después', '溪山之圍——七十七日的包圍，五個月後基地被放棄', '溪山之围——七十七日的包围，五个月后基地被放弃', 'Siège de Khe Sanh — soixante-dix-sept jours d’encerclement, et une base abandonnée cinq mois plus tard', '케산 포위전 — 77일의 포위, 그리고 다섯 달 뒤 버려진 기지') },
    { d: '1968-01-30', d2: '1968-03-28', at: 'Saigon', wiki: 'Tet_Offensive', kind: 'battle', name: L('The Tết Offensive — over a hundred towns attacked at once, a military defeat that ended American confidence in the war', 'テト攻勢——100を超える町が同時に攻撃される。軍事的には敗北だが、アメリカの戦争への確信を終わらせた', 'Die Tết-Offensive — über hundert Städte gleichzeitig angegriffen; eine militärische Niederlage, die das amerikanische Vertrauen in den Krieg beendete', 'Тетское наступление — одновременный удар более чем по сотне городов: военное поражение, покончившее с уверенностью Америки в этой войне', 'La ofensiva del Tết: más de cien ciudades atacadas a la vez, una derrota militar que acabó con la confianza estadounidense en la guerra', '春節攻勢——逾百座城鎮同時遇襲；軍事上的失敗，卻終結了美國對這場戰爭的信心', '春节攻势——逾百座城镇同时遇袭；军事上的失败，却终结了美国对这场战争的信心', 'L’offensive du Tết — plus de cent villes attaquées à la fois, une défaite militaire qui a mis fin à la confiance américaine dans la guerre', '뗏 공세 — 백 곳이 넘는 도시가 동시에 공격받다. 군사적 패배였으나 미국의 전쟁에 대한 확신을 끝냈다') },
    { d: '1968-01-31', d2: '1968-03-02', at: 'Hue', wiki: 'Battle_of_Huế', kind: 'battle', name: L('Battle of Huế — a month of street fighting for the citadel, and most of the old imperial city destroyed', 'フエの戦い——城塞をめぐる1か月の市街戦。旧王城のほとんどが破壊された', 'Schlacht um Huế — ein Monat Straßenkampf um die Zitadelle, und der größte Teil der alten Kaiserstadt zerstört', 'Битва за Хюэ — месяц уличных боёв за цитадель; большая часть старой императорской столицы разрушена', 'Batalla de Huế: un mes de combate callejero por la ciudadela y la mayor parte de la vieja capital imperial destruida', '順化之戰——為爭奪城堡進行了一個月的巷戰，舊皇城大半被毀', '顺化之战——为争夺城堡进行了一个月的巷战，旧皇城大半被毁', 'Bataille de Huế — un mois de combats de rue pour la citadelle, et la vieille cité impériale détruite pour l’essentiel', '후에 전투 — 성채를 둘러싼 한 달간의 시가전, 옛 황성의 대부분이 파괴되다') },
    { d: '1968-01-31', d2: '1968-02-28', at: 'Hue', wiki: 'Massacre_at_Huế', kind: 'atrocity', cas: [2800, 6000], name: L('Massacre at Huế — thousands taken from lists and killed during the month the city was held', 'フエ虐殺——市が保持された1か月の間に、名簿によって連行された数千人が殺害される', 'Massaker von Huế — Tausende nach Listen verschleppt und getötet, während die Stadt gehalten wurde', 'Резня в Хюэ — тысячи людей, взятых по спискам и убитых за месяц, пока город удерживался', 'Masacre de Huế: miles de personas sacadas de unas listas y asesinadas durante el mes en que la ciudad estuvo ocupada', '順化屠殺——在該市被佔的一個月間，數千人按名單被帶走並殺害', '顺化屠杀——在该市被占的一个月间，数千人按名单被带走并杀害', 'Massacre de Huế — des milliers de personnes enlevées sur listes et tuées pendant le mois d’occupation de la ville', '후에 학살 — 도시가 점령된 한 달 사이, 명부에 따라 끌려간 수천 명이 살해되다') },
    { d: '1968-03-16', at: 'My Lai', wiki: 'My_Lai_massacre', kind: 'atrocity', cas: [347, 504], name: L('My Lai massacre — an American company kills the unarmed inhabitants of Sơn Mỹ in a morning', 'ソンミ村虐殺——アメリカ軍の1個中隊が、ひと朝でソンミ村の非武装の住民を殺害する', 'Massaker von Mỹ Lai — eine amerikanische Kompanie tötet an einem Vormittag die unbewaffneten Bewohner von Sơn Mỹ', 'Резня в Милай — американская рота за одно утро убивает безоружных жителей Шонми', 'Masacre de My Lai: una compañía estadounidense mata en una mañana a los habitantes desarmados de Sơn Mỹ', '美萊村屠殺——一個美軍連在一個上午殺害山美村手無寸鐵的居民', '美莱村屠杀——一个美军连在一个上午杀害山美村手无寸铁的居民', 'Massacre de Mỹ Lai — une compagnie américaine tue en une matinée les habitants désarmés de Sơn Mỹ', '미라이 학살 — 미군 1개 중대가 한나절 만에 선미 마을의 비무장 주민들을 살해하다') },
    { d: '1968-11-15', d2: '1972-03-29', at: 'Tchepone', wiki: 'Operation_Commando_Hunt', kind: 'air', name: L('Operation Commando Hunt — three and a half years of interdiction over the trail, and the traffic went on', 'コマンドー・ハント作戦——ホーチミン・ルート遮断のための3年半。それでも輸送は続いた', 'Operation Commando Hunt — dreieinhalb Jahre Unterbindungskrieg über dem Pfad, und der Verkehr ging weiter', 'Операция «Коммандо хант» — три с половиной года ударов по тропе; движение по ней не прекратилось', 'Operación Commando Hunt: tres años y medio de interdicción sobre la ruta, y el tráfico siguió', '「突擊獵殺」行動——對小道實施三年半的阻絕轟炸，運輸依舊未斷', '“突击猎杀”行动——对小道实施三年半的阻绝轰炸，运输依旧未断', 'Opération Commando Hunt — trois ans et demi d’interdiction au-dessus de la piste, et le trafic a continué', '커맨도 헌트 작전 — 3년 반에 걸친 루트 차단 폭격, 그럼에도 수송은 이어졌다') },
    { d: '1969-03-18', d2: '1970-05-26', at: 'Memot', wiki: 'Operation_Menu', kind: 'air', name: L('Operation Menu — fourteen months of bombing inside neutral Cambodia, concealed from Congress', 'メニュー作戦——中立国カンボジア領内への14か月の爆撃。議会には隠されていた', 'Operation Menu — vierzehn Monate Bombardierung im neutralen Kambodscha, vor dem Kongress verborgen', 'Операция «Меню» — четырнадцать месяцев бомбардировок на территории нейтральной Камбоджи, скрытых от Конгресса', 'Operación Menu: catorce meses de bombardeos dentro de la Camboya neutral, ocultados al Congreso', '「菜單」行動——對中立國柬埔寨境內進行十四個月的轟炸，並對國會隱瞞', '“菜单”行动——对中立国柬埔寨境内进行十四个月的轰炸，并对国会隐瞒', 'Opération Menu — quatorze mois de bombardements à l’intérieur du Cambodge neutre, cachés au Congrès', '메뉴 작전 — 중립국 캄보디아 영내에 대한 14개월간의 폭격, 의회에는 감춰졌다') },
    { d: '1969-05-10', d2: '1969-05-20', at: 'A Luoi', wiki: 'Battle_of_Hamburger_Hill', kind: 'battle', name: L('Hamburger Hill — Đồi A Bia in the A Sầu valley is taken in eleven days and abandoned in seventeen', 'ハンバーガー・ヒル——アシャウ渓谷のアビア山を11日かけて奪い、17日後に放棄する', 'Hamburger Hill — der Đồi A Bia im A-Sầu-Tal wird in elf Tagen genommen und nach siebzehn Tagen geräumt', '«Гамбургерская высота» — Аби́а в долине Ашау взята за одиннадцать дней и оставлена через семнадцать', 'La Colina Hamburguesa: el Đồi A Bia, en el valle de A Sầu, se toma en once días y se abandona a los diecisiete', '漢堡高地——阿邵谷的Đồi A Bia歷十一日攻下，十七日後即被放棄', '汉堡高地——阿绍谷的Đồi A Bia历十一日攻下，十七日后即被放弃', 'Hamburger Hill — le Đồi A Bia, dans la vallée d’A Sầu, est pris en onze jours et abandonné dix-sept jours plus tard', '햄버거 힐 — 아사우 계곡의 아비아 고지를 11일 만에 빼앗고 17일 만에 버리다') },
    { d: '1969-06-08', at: 'Midway', wiki: 'Vietnamization', kind: 'conference', name: L('At Midway, Nixon and Thiệu announce the first American withdrawal: Vietnamization begins', 'ミッドウェーでニクソンとチューが最初のアメリカ軍撤退を発表——ベトナム化が始まる', 'Auf Midway kündigen Nixon und Thiệu den ersten amerikanischen Truppenabzug an: die Vietnamisierung beginnt', 'На Мидуэе Никсон и Тхьеу объявляют о первом выводе американских войск: начинается вьетнамизация', 'En Midway, Nixon y Thiệu anuncian la primera retirada estadounidense: comienza la vietnamización', '尼克森與阮文紹在中途島宣布首次美軍撤離：越南化開始', '尼克松与阮文绍在中途岛宣布首次美军撤离：越南化开始', 'À Midway, Nixon et Thiệu annoncent le premier retrait américain : la vietnamisation commence', '미드웨이에서 닉슨과 티에우가 첫 미군 철수를 발표하다 — 베트남화가 시작되다') },
    { d: '1970-03-18', at: 'Phnom Penh', wiki: '1970_Cambodian_coup', kind: 'political', name: L('Sihanouk is deposed in Phnom Penh and Cambodia’s neutrality ends', 'プノンペンでシハヌークが解任され、カンボジアの中立が終わる', 'Sihanouk wird in Phnom Penh abgesetzt, und Kambodschas Neutralität endet', 'В Пномпене низложен Сианук, и нейтралитет Камбоджи кончается', 'Sihanouk es depuesto en Phnom Penh y termina la neutralidad de Camboya', '施亞努在金邊被廢黜，柬埔寨的中立就此終結', '西哈努克在金边被废黜，柬埔寨的中立就此终结', 'Sihanouk est déposé à Phnom Penh et la neutralité du Cambodge prend fin', '프놈펜에서 시아누크가 축출되고 캄보디아의 중립이 끝나다') },
    { d: '1970-04-29', d2: '1970-07-22', at: 'Snuol', wiki: 'Cambodian_campaign', kind: 'battle', name: L('The Cambodian incursion — American and ARVN forces cross into the border sanctuaries, and the war in the United States comes to the campuses', 'カンボジア侵攻——米軍と南ベトナム軍が国境の聖域へ越境する。アメリカ国内では戦争が大学へ及ぶ', 'Der Einmarsch in Kambodscha — amerikanische und ARVN-Verbände stoßen in die Rückzugsgebiete an der Grenze vor, und in den USA erreicht der Krieg die Universitäten', 'Камбоджийское вторжение — американские и южновьетнамские войска входят в приграничные «убежища», а в США война доходит до университетов', 'La incursión en Camboya: fuerzas estadounidenses y del ARVN entran en los santuarios fronterizos, y en Estados Unidos la guerra llega a los campus', '柬埔寨入侵——美軍與南越軍越境進入邊境庇護所，美國國內的反戰浪潮延燒至校園', '柬埔寨入侵——美军与南越军越境进入边境庇护所，美国国内的反战浪潮延烧至校园', 'L’incursion au Cambodge — les forces américaines et de l’ARVN pénètrent dans les sanctuaires frontaliers, et aux États-Unis la guerre gagne les campus', '캄보디아 침공 — 미군과 남베트남군이 국경의 성역으로 넘어가고, 미국 안에서는 전쟁이 대학으로 번지다') },
    { d: '1971-02-08', d2: '1971-03-25', at: 'Tchepone', wiki: 'Operation_Lam_Son_719', kind: 'battle', name: L('Lam Sơn 719 — the ARVN drives into Laos without American advisers and comes back broken', 'ラム・ソン719——南ベトナム軍が米軍顧問なしでラオスへ進攻し、壊乱して戻る', 'Lam Sơn 719 — die ARVN stößt ohne amerikanische Berater nach Laos vor und kommt zerschlagen zurück', '«Ламшон 719» — АРВ вторгается в Лаос без американских советников и возвращается разбитой', 'Lam Sơn 719: el ARVN penetra en Laos sin asesores estadounidenses y vuelve deshecho', '藍山719號行動——南越軍在無美軍顧問隨行下進攻寮國，潰散而歸', '蓝山719号行动——南越军在无美军顾问随行下进攻老挝，溃散而归', 'Lam Sơn 719 — l’ARVN pénètre au Laos sans conseillers américains et en revient brisée', '람선 719 — 남베트남군이 미군 고문 없이 라오스로 진격했다가 무너져 돌아오다') },
    { d: '1972-03-30', d2: '1972-10-22', at: 'Dong Ha', wiki: 'Easter_Offensive', kind: 'battle', name: L('The Easter Offensive — the North attacks on three axes with fourteen divisions and armour, and for six months the war has front lines again', '復活祭攻勢——北ベトナムが14個師団と戦車で3方面から攻勢に出る。6か月のあいだ、この戦争は再び戦線を持つ', 'Die Osteroffensive — der Norden greift auf drei Achsen mit vierzehn Divisionen und Panzern an, und ein halbes Jahr lang hat der Krieg wieder Frontlinien', 'Пасхальное наступление — Север бьёт по трём направлениям четырнадцатью дивизиями с танками, и полгода у войны снова есть линии фронта', 'La ofensiva de Pascua: el Norte ataca en tres ejes con catorce divisiones y blindados, y durante seis meses la guerra vuelve a tener frentes', '復活節攻勢——北方以十四個師與裝甲部隊三路進攻，此後半年這場戰爭重新有了戰線', '复活节攻势——北方以十四个师与装甲部队三路进攻，此后半年这场战争重新有了战线', 'L’offensive de Pâques — le Nord attaque sur trois axes avec quatorze divisions et des blindés, et pendant six mois la guerre retrouve des lignes de front', '부활절 공세 — 북측이 14개 사단과 기갑으로 세 방면에서 공격하고, 여섯 달 동안 이 전쟁은 다시 전선을 갖는다') },
    { d: '1972-04-13', d2: '1972-07-20', at: 'An Loc', wiki: 'Battle_of_An_Lộc', kind: 'siege', name: L('Siege of An Lộc — a town of two square kilometres holds out for ninety-five days on airdrops', 'アンロクの包囲——面積2平方キロの町が、空中投下だけで95日間持ちこたえる', 'Belagerung von An Lộc — eine Stadt von zwei Quadratkilometern hält fünfundneunzig Tage lang aus, versorgt nur aus der Luft', 'Осада Анлока — городок площадью два квадратных километра держится девяносто пять дней на снабжении по воздуху', 'Asedio de An Lộc: una ciudad de dos kilómetros cuadrados resiste noventa y cinco días abastecida por aire', '安祿之圍——面積僅兩平方公里的市鎮，僅靠空投堅守九十五日', '安禄之围——面积仅两平方公里的市镇，仅靠空投坚守九十五日', 'Siège d’An Lộc — une ville de deux kilomètres carrés tient quatre-vingt-quinze jours, ravitaillée par air', '안록 포위전 — 2제곱킬로미터의 소도시가 공중 투하만으로 95일을 버티다') },
    { d: '1972-04-14', d2: '1972-05-31', at: 'Kon Tum', wiki: 'Battle_of_Kontum', kind: 'siege', name: L('Battle of Kon Tum — the Highlands axis of the offensive is stopped at the provincial capital', 'コントゥムの戦い——攻勢の中部高原方面は、省都で食い止められる', 'Schlacht um Kon Tum — die Hochland-Stoßrichtung der Offensive wird an der Provinzhauptstadt aufgehalten', 'Бой за Контум — горное направление наступления остановлено у столицы провинции', 'Batalla de Kon Tum: el eje de la ofensiva en las Tierras Altas se detiene en la capital provincial', '昆嵩之戰——攻勢的中部高原一路在省會被擋下', '昆嵩之战——攻势的中部高原一路在省会被挡下', 'Bataille de Kon Tum — l’axe de l’offensive sur les Hauts Plateaux est stoppé à la capitale provinciale', '꼰뚬 전투 — 공세의 고원 방면이 성도에서 저지되다') },
    { d: '1972-05-09', at: 'Haiphong', wiki: 'Operation_Pocket_Money', kind: 'naval', name: L('Operation Pocket Money — Hải Phòng and the northern ports are mined from the air', 'ポケット・マネー作戦——ハイフォンと北部の港湾が空中から機雷封鎖される', 'Operation Pocket Money — Hải Phòng und die nördlichen Häfen werden aus der Luft vermint', 'Операция «Покет мани» — Хайфон и северные порты минируются с воздуха', 'Operación Pocket Money: Hải Phòng y los puertos del norte son minados desde el aire', '「零用錢」行動——海防與北方各港自空中布雷封鎖', '“零用钱”行动——海防与北方各港自空中布雷封锁', 'Opération Pocket Money — Hải Phòng et les ports du nord sont minés par voie aérienne', '포켓 머니 작전 — 하이퐁과 북부 항구들이 공중에서 기뢰로 봉쇄되다') },
    { d: '1972-05-10', d2: '1972-10-23', at: 'Hanoi', wiki: 'Operation_Linebacker', kind: 'air', name: L('Operation Linebacker — the bombing of the North resumes, this time against its railways, bridges and fuel', 'ラインバッカー作戦——北爆が再開される。今回の標的は鉄道・橋梁・燃料である', 'Operation Linebacker — die Bombardierung des Nordens wird wieder aufgenommen, diesmal gegen Eisenbahnen, Brücken und Treibstoff', 'Операция «Лайнбэкер» — бомбардировки Севера возобновляются, теперь против железных дорог, мостов и горючего', 'Operación Linebacker: se reanuda el bombardeo del Norte, ahora contra sus ferrocarriles, puentes y combustible', '「後衛」行動——恢復對北方的轟炸，此次目標為鐵路、橋樑與燃料', '“后卫”行动——恢复对北方的轰炸，此次目标为铁路、桥梁与燃料', 'Opération Linebacker — les bombardements du Nord reprennent, cette fois contre ses voies ferrées, ses ponts et ses carburants', '라인배커 작전 — 북폭이 재개되다. 이번 표적은 철도·교량·연료다') },
    { d: '1972-12-18', d2: '1972-12-29', at: 'Hanoi', wiki: 'Operation_Linebacker_II', kind: 'air', name: L('Operation Linebacker II — eleven days of B-52 raids on Hanoi and Hải Phòng over Christmas', 'ラインバッカーII作戦——クリスマスを挟む11日間、B-52がハノイとハイフォンを空襲する', 'Operation Linebacker II — elf Tage B-52-Angriffe auf Hanoi und Hải Phòng über Weihnachten', 'Операция «Лайнбэкер II» — одиннадцать дней рейдов B-52 на Ханой и Хайфон под Рождество', 'Operación Linebacker II: once días de incursiones de B-52 sobre Hanói y Hải Phòng en Navidad', '「後衛二號」行動——聖誕期間十一日，B-52轟炸河內與海防', '“后卫二号”行动——圣诞期间十一日，B-52轰炸河内与海防', 'Opération Linebacker II — onze jours de raids de B-52 sur Hanoï et Hải Phòng pendant Noël', '라인배커 II 작전 — 성탄절을 낀 11일간 B-52가 하노이와 하이퐁을 폭격하다') },
    { d: '1973-01-27', at: 'Paris', wiki: 'Paris_Peace_Accords', kind: 'political', name: L('The Paris Peace Accords — a ceasefire in place, the Americans leave, and both armies stay where they stand', 'パリ和平協定——現状のままの停戦。アメリカ軍は撤退し、両軍はいた場所にとどまる', 'Das Pariser Abkommen — Waffenstillstand an Ort und Stelle, die Amerikaner gehen, und beide Armeen bleiben, wo sie stehen', 'Парижские соглашения — прекращение огня на занимаемых позициях, американцы уходят, обе армии остаются там, где стоят', 'Los Acuerdos de París: alto el fuego sobre el terreno, los estadounidenses se van y ambos ejércitos se quedan donde están', '巴黎和平協定——就地停火，美軍撤離，兩軍各留原地', '巴黎和平协定——就地停火，美军撤离，两军各留原地', 'Les accords de paix de Paris — cessez-le-feu sur place, les Américains partent, et les deux armées restent où elles sont', '파리 평화 협정 — 현 위치 휴전, 미군은 떠나고 두 군대는 서 있던 자리에 남는다') },
    { d: '1974-12-13', d2: '1975-01-06', at: 'Phuoc Long', wiki: 'Battle_of_Phuoc_Long', kind: 'battle', name: L('Battle of Phước Long — a province falls and the United States does not come back; Hanoi has its answer', 'フォクロンの戦い——1つの省が陥落しても、アメリカは戻ってこなかった。ハノイは答えを得る', 'Schlacht um Phước Long — eine Provinz fällt, und die Vereinigten Staaten kehren nicht zurück; Hanoi hat seine Antwort', 'Бой за Фыоклонг — провинция пала, а Соединённые Штаты не вернулись; Ханой получил ответ', 'Batalla de Phước Long: cae una provincia y Estados Unidos no regresa; Hanói tiene su respuesta', '福隆之戰——一省陷落，而美國並未回頭；河內得到了答案', '福隆之战——一省陷落，而美国并未回头；河内得到了答案', 'Bataille de Phước Long — une province tombe et les États-Unis ne reviennent pas ; Hanoï a sa réponse', '푸옥롱 전투 — 한 성이 함락되어도 미국은 돌아오지 않았다. 하노이는 답을 얻는다') },
    { d: '1975-03-10', d2: '1975-03-11', at: 'Ban Me Thuot', wiki: 'Battle_of_Ban_Me_Thuot', kind: 'battle', name: L('Ban Mê Thuột falls in thirty-two hours, and the order to abandon the Central Highlands follows', 'バンメトートが32時間で陥落し、中部高原放棄の命令がそれに続く', 'Ban Mê Thuột fällt in zweiunddreißig Stunden, und der Befehl zur Räumung des zentralen Hochlands folgt', 'Банметхуот падает за тридцать два часа, и следом отдан приказ оставить Центральное плато', 'Ban Mê Thuột cae en treinta y dos horas, y a continuación llega la orden de abandonar las Tierras Altas Centrales', '邦美蜀於三十二小時內陷落，放棄中部高原的命令隨之而下', '邦美蜀于三十二小时内陷落，放弃中部高原的命令随之而下', 'Ban Mê Thuột tombe en trente-deux heures, et suit l’ordre d’abandonner les Hauts Plateaux', '반메투옷이 32시간 만에 함락되고, 중부 고원 포기 명령이 뒤따르다') },
    { d: '1975-03-21', d2: '1975-03-29', at: 'Da Nang', wiki: 'Huế–Đà_Nẵng_Campaign', kind: 'battle', name: L('The Huế–Đà Nẵng campaign — two cities and the whole northern corps area go in nine days', 'フエ・ダナン戦役——2つの都市と北部軍団管区の全域が、9日で失われる', 'Der Feldzug um Huế und Đà Nẵng — zwei Städte und der gesamte nördliche Korpsbereich fallen in neun Tagen', 'Кампания Хюэ — Дананг: два города и вся северная корпусная зона потеряны за девять дней', 'La campaña de Huế–Đà Nẵng: dos ciudades y toda la zona del cuerpo norte se pierden en nueve días', '順化—峴港戰役——兩座城市與整個北部軍區於九日內盡失', '顺化—岘港战役——两座城市与整个北部军区于九日内尽失', 'La campagne de Huế–Đà Nẵng — deux villes et toute la zone du corps nord tombent en neuf jours', '후에–다낭 전역 — 두 도시와 북부 군단 관구 전체가 아흐레 만에 사라지다') },
    { d: '1975-04-09', d2: '1975-04-21', at: 'Xuan Loc', wiki: 'Battle_of_Xuan_Loc', kind: 'battle', name: L('Battle of Xuân Lộc — the ARVN 18th Division holds the last gate to Saigon for twelve days', 'スアンロクの戦い——南ベトナム軍第18師団が、サイゴンへの最後の門を12日間守り抜く', 'Schlacht von Xuân Lộc — die 18. ARVN-Division hält zwölf Tage lang das letzte Tor nach Saigon', 'Бой за Суанлок — 18-я дивизия АРВ двенадцать дней удерживает последние ворота к Сайгону', 'Batalla de Xuân Lộc: la 18.ª División del ARVN defiende doce días la última puerta a Saigón', '春祿之戰——南越軍第十八師守住通往西貢的最後門戶十二日', '春禄之战——南越军第十八师守住通往西贡的最后门户十二日', 'Bataille de Xuân Lộc — la 18e division de l’ARVN tient douze jours la dernière porte de Saigon', '쑤언록 전투 — 남베트남군 제18사단이 사이공으로 가는 마지막 관문을 열이틀 지키다') },
    { d: '1975-04-26', d2: '1975-04-30', at: 'Saigon', wiki: 'Ho_Chi_Minh_Campaign', kind: 'battle', name: L('The Hồ Chí Minh campaign — five columns close on Saigon from five directions', 'ホーチミン作戦——5個の縦隊が5方向からサイゴンに迫る', 'Der Hồ-Chí-Minh-Feldzug — fünf Kolonnen schließen aus fünf Richtungen auf Saigon', 'Операция «Хо Ши Мин» — пять колонн сходятся к Сайгону с пяти направлений', 'La campaña Hồ Chí Minh: cinco columnas convergen sobre Saigón desde cinco direcciones', '胡志明戰役——五路縱隊自五個方向合圍西貢', '胡志明战役——五路纵队自五个方向合围西贡', 'La campagne Hồ Chí Minh — cinq colonnes convergent sur Saigon depuis cinq directions', '호찌민 작전 — 다섯 개 종대가 다섯 방향에서 사이공을 조여들다') },
    { d: '1975-04-29', d2: '1975-04-30', at: 'Saigon', wiki: 'Operation_Frequent_Wind', kind: 'air', name: L('Operation Frequent Wind — the last Americans and some seven thousand others are lifted out by helicopter', 'フリークエント・ウィンド作戦——最後のアメリカ人と約7千人が、ヘリコプターで運び出される', 'Operation Frequent Wind — die letzten Amerikaner und rund siebentausend weitere Menschen werden per Hubschrauber ausgeflogen', 'Операция «Порывистый ветер» — последних американцев и около семи тысяч других вывозят вертолётами', 'Operación Frequent Wind: los últimos estadounidenses y unas siete mil personas más son evacuados en helicóptero', '「常風」行動——最後的美國人與約七千人以直升機撤離', '“常风”行动——最后的美国人与约七千人以直升机撤离', 'Opération Frequent Wind — les derniers Américains et quelque sept mille autres personnes sont évacués par hélicoptère', '프리퀀트 윈드 작전 — 마지막 미국인들과 약 7천 명이 헬리콥터로 실려 나가다') },
    { d: '1975-04-30', at: 'Saigon', wiki: 'Fall_of_Saigon', kind: 'political', name: L('The fall of Saigon — a tank comes through the palace gate at 11:30 and the Republic of Vietnam surrenders', 'サイゴン陥落——11時30分、戦車が大統領官邸の門を破り、ベトナム共和国は降伏する', 'Der Fall von Saigon — um 11:30 Uhr durchbricht ein Panzer das Palasttor, und die Republik Vietnam kapituliert', 'Падение Сайгона — в 11:30 танк проходит через ворота дворца, и Республика Вьетнам капитулирует', 'La caída de Saigón: a las 11:30 un tanque atraviesa la verja del palacio y la República de Vietnam se rinde', '西貢陷落——十一時三十分坦克撞開總統府大門，越南共和國投降', '西贡陷落——十一时三十分坦克撞开总统府大门，越南共和国投降', 'La chute de Saigon — à 11 h 30 un char franchit la grille du palais et la République du Viêt Nam capitule', '사이공 함락 — 11시 30분 전차가 관저 정문을 뚫고 들어오고, 베트남 공화국이 항복하다') },
  /* ⚠ SORTED HERE RATHER THAN BY HAND, for the same reason ./ww1.mjs sorts: the build requires date
     order and the block above is written so a reader can follow it. Array.prototype.sort is stable,
     so two operations that begin on the same day keep the order they were written in — which is why
     the battle for Huế stands before the massacre in it. */
  ].sort((a, b) => (a.d < b.d ? -1 : a.d > b.d ? 1 : 0)),
};

export { VIETNAM };
